## 
# SEAM 3D illumination
##
try:    from rsf.cluster import *
except: from rsf.proj    import *
import rsf.recipes.wplot as wplot
import rsf.recipes.encode as encode
import rsf.recipes.wei as wei

Cluster(name='3DSEAMIll',email='lewisli@stanford.edu', time=5, ppn=1, nodetype='Q26a', scheduler='pbs')


par = dict(
     nx=875,  ox=0, dx=0.04, lx='x', ux='km',
     ny=1000, oy=0, dy=0.04, ly='y', uy='km',
     nz=750,  oz=0, dz=0.02, lz='z', uz='km',
     nt=6000, ot=0, dt=0.001,lt='t', ut='s'
     )
wplot.param(par)      # prepare plots

# WEI params
par['jw']=1
par['ow']=3
par['nw']=24
par['nrmax']=5
        
# ------------------------------------------------------------
# velocity
strvelfile = '/data/groups/scrf/data/seam/Vp_xyz_10m.hh'
Flow('velo',None,
     '''
     window squeeze=n <%s n1=%d j1=4 n2=%d j2=4 n3=%d j3=2 |
     scale rscale=0.001 |
     put 
     o1=%g d1=%g label1=%s unit1=%s
     o2=%g d2=%g label2=%s unit2=%s
     o3=%g d3=%g label3=%s unit3=%s
     '''%(strvelfile,
          par['nx'],par['ny'],par['nz'],
          par['ox'],par['dx'],par['lx'],par['ux'],
          par['oy'],par['dy'],par['ly'],par['uy'],
          par['oz'],par['dz'],par['lz'],par['uz']
          ))
Flow('vbyt','velo',
     '''
     transp plane=23 | transp plane=12 |
     byte gainpanel=a pclip=100 mean=y
     ''')
Result('velo','vbyt',wplot.igrey3d('color=j frame1=500',par))

# slowness
Flow('slow','velo','math output="1/input"')

# data - a plane wave
Flow('tdat',None,
     '''
     spike nsp=1 mag=1
     n1=%(nt)d o1=%(ot)g d1=%(dt)g k1=1 l1=1
     n2=%(nx)d o2=%(ox)g d2=%(dx)g
     n3=%(ny)d o3=%(oy)g d3=%(dy)g |
     put label1=%(lt)s unit1=%(ut)s label2=%(lx)s unit2=%(ux)s label3=%(ly)s unit3=%(uy)s
     '''%par)
encode.time2freq('tdat','wdat',par)

# wavefield
wei.wfl('wfld','wdat','slow','',par)

# illumination
for iw in range(par['nw']):
     wtag = "%02d"%iw
     Flow('ilum'+wtag,'wfld',
          'window n4=1 f4=%d | cabs | transp plane=23 | transp plane=12'%iw)
Flow('ilum',['ilum%02d'%iw for iw in range(par['nw'])],
     'add ${SOURCES[1:%(nw)d]}'%par)
Flow('ibyt','ilum',
     'byte gainpanel=a pclip=99.0 mean=y')
Result('ilum','ibyt',wplot.igrey3d('color=j frame1=500',par))

Flow('ionv',['velo','ilum'],
     'transp plane=23 | transp plane=12 | add scale=1,3 ${SOURCES[1]}')
Flow('obyt','ionv',
     'byte gainpanel=a pclip=99.0 mean=y frame1=500')
Result('ionv','obyt',wplot.igrey3d('',par))

End()
